### ISSUE TITLE
Usages Build is failing with error "The just-the-docs theme could not be found. "

### ISSUE THREAD

**Issue by amitsharma8603** [just-the-docs/just-the-docs-template#40] opened 2024-01-18 10:36 UTC
Hi, I am trying to use just-the-doc repository. 
I have switched on usages of Gitpages in my repository and switched on actions as source.
Build is failing with error "The just-the-docs theme could not be found.". 
Can you please support me what to do here?
Thanks in advance..

<img width="897" alt="image" src="https://github.com/just-the-docs/just-the-docs-template/assets/101014531/ff7b1494-2aa2-4dd7-ac03-5a48a7121dd2">

**Comment by mattxwang** [comment] 2024-01-24 22:36
Hi @amitsharma8603, thanks for making an issue! I'm going to close this as a duplicate of https://github.com/just-the-docs/just-the-docs/discussions/1418.

**Closed by mattxwang** 2024-01-24 22:36 UTC
